### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by zsommk** [revvv/gdash-export-CrLi#1]
the game crashes when the "particle effect" tab is detached in game graphics in preferences.

**Comment by revvv** [comment]
Can't reproduce it on Windows 10. The program just restarts which is intended.

**Comment by zsommk** [comment]
Hi
thanks for the answer

Game freezes when:
uncheck the "Particle effect" tab in Play - Preferences - Game graphics.
And we will run Cave editor - view - edit cave. And now the program is suspended.

I searched for a long time for the cause of the game crashing in the editor, and that's when I discovered it.

This effect occurs under windows 10, windows 11 or linux mint 21.1 on different computers.

Kind regards

**Comment by revvv** [comment]
Oh, thank you very much. I guess the updated GTK libs caused the problem. Fixed.

**Comment by zsommk** [comment]
Thank you.

Regards

sob., 10 cze 2023 o 16:38 revvv ***@***.***> napisał(a):
