### ISSUE TITLE
Cave properties window is too big

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#13]
The cave properties window is a little bit too big for some systems. If monitor resolution is not high enough the cave properties window is not completely displayed. If so settings could not be acknowledged.

**Comment by cwscws** [comment]
As acknowledging with RETURN (or quitting with ESC) I do not see this as a big problem. Screen resolution has to be way lower than full HD to become problematic and I do not think there are many users out there with such low screen resolutions.

**Comment by revvv** [comment]
I don't know if there is a simpler solution, but I really don't want to add a GtkGrid. The window is created here:
[src/editor/editor.cpp](https://github.com/revvv/gdash-export-CrLi/blob/945fba6f2a8addddb01bdb2d81d0a8f1fa6f03f0/src/editor/editor.cpp#L580)

I guess every OS has a way to move around windows that are too big for the screen. Could you try that?
