### ISSUE TITLE
Feature request: more theme songs

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#14]
At the moment only bd1.ogg and bd2.ogg are played randomly. What about adding more files (e.g. bd3.ogg, bd4.ogg, etc.)? If e.g. bd3.ogg is available it will be included in the random selection of themes - if not, only bd1 and bd2 is used.

More title music files could be added like this one:
https://www.youtube.com/watch?v=enE1m34Ip4E
https://www.youtube.com/watch?v=wttOKgQVoxA
https://www.youtube.com/watch?v=sdM7Rq20tIc
https://www.youtube.com/watch?v=JDQbOSh_Bi4
https://www.youtube.com/watch?v=ckRukbygASQ
https://www.youtube.com/watch?v=6b9HKkIl04Q
https://www.youtube.com/watch?v=HuqFgcqAD7o
https://www.youtube.com/watch?v=2kqufCg0LnM

**Comment by revvv** [comment]
I have converted the videos to ogg: 19,3 MB
That would increase the distribution a lot. Maybe a separate download?

**Comment by cwscws** [comment]
Oh, nice!

It wasn’t my intention to add new music files to the distribution - only wanted the possibility to add music by myself just using the file names bd3.ogg, bd4.ogg, bd5.ogg and so on. If GDash notices a bd3.ogg or even e.g. a bd14.ogg it should be added to the random selection of title musics.

But if you want to you can offer this collection with a separate download.

**Comment by revvv** [comment]
By default GDash considers each .ogg file in the music folder!

**Comment by cwscws** [comment]
Ok, then no additional code has to be added. Just provide the additional themes as a separate download.
