### ISSUE TITLE
Errors in replays with POT element

### ISSUE THREAD

**Issue by zsommk** [revvv/gdash-export-CrLi#18]
In cave replays that have a POT item and the player uses it, the replay no longer plays correctly.

**Comment by revvv** [comment]
I created a very simple cave: Replay works correctly. Can you give me an example?

**Comment by zsommk** [comment]
As long as you are in the game, replays with these caves are fine.
However, if you save your game so you don't lose your replays, you will end the game.
It is after restarting Gdash that the replays with the POT element used will already be wrong.

**Comment by revvv** [comment]
Indeed pushing fire is not stored in a .bd file, so Rockford cannot leave the "stirring pot" status. New release for Windows is out.
Please test. It might have bad side effects, because "FIRE" was never stored before...

**Comment by zsommk** [comment]
Hi. You are amazing.

Replays from version 1.8.1 work very well.
Moreover, replays made with version 1.8.1 work on all Gdash backwards, even
the year 2010 version.

Regards

pt., 4 sie 2023 o 15:00 revvv ***@***.***> napisał(a):
