### ISSUE TITLE
An invisible outbox is visible

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#19]
../caves/Alan_Bond/Boulder_Brain.gds - Cave 09
GDash Cave Editor shows the invisible outbox in the left bottom corner.
But the exit is visible during the game: https://youtu.be/sN6l4oEODNI?t=144

**Comment by revvv** [comment]
I tried this cave on Windows, reduced required diamonds to 1 and if I get 1 diamond the outbox does NOT flash.
What version/OS are you using?

**Comment by renyxadarox** [comment]
Windows 10 Enterprise LTSC 21H2

**Comment by revvv** [comment]
Which GDash version? Does this happen with any cave with a hidden outbox? Even a simple one?

**Comment by renyxadarox** [comment]
gdash-export-1.8-win-64
The app calls itself GDashexport-1.7-fork

Yes, this happens even in a simple cave.
I set 2 exits, one visible (top), one invisible (left), 1 required diamond and both exits are flashing:
https://youtu.be/P_GXArzNKAY

**Comment by revvv** [comment]
Try Edit -> Preferences -> No invisible outbox: UNCHECK

**Comment by renyxadarox** [comment]
Yeah, now it works as expected!
Is the setting checked by default?
I definitely never touch it.

**Comment by revvv** [comment]
It's not set by default. Either delete `gdash.ini` or use `--default-settings`
