### ISSUE TITLE
Mac: Menus not clickable by mouse

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#2]
The main menus can be opened by mouse but the opened menus do not react on any mouse movement or click.

I'm excited that finally somebody is taking care of GDash! :) I was involved in the development phase with testing, bug reports, translation, graphics, etc. As I do not know how to contact you here maybe you can email me at shabanak@gmx.net

**Comment by revvv** [comment]
I guess you are testing Mac OS? Which version? And probably you installed the ZIP distribution? (The dmg is brand new)
I already noticed that the menus don't open right after the first run, but after a restart they work.
I have no idea why this is the case. Is your case reproducible?

**Comment by cwscws** [comment]
M1 iMac with Ventura. Copied from the DMG into Applications. You mean restart the computer? Weird if this would help. I remember there was something similar on VICE a while ago but I’m no programmer so I do not know what they did.

**Comment by revvv** [comment]
> You mean restart the computer?

No, just restart the game. Maybe you could test the ZIP distribution, too?

**Comment by revvv** [comment]
Seems to be a GTK+3 problem.

@cwscws gave me these links:
https://gitlab.gnome.org/GNOME/gtk/-/issues/5305
https://sourceforge.net/p/vice-emu/bugs/1776/

Version used was gtk+3 3.24.37. I'll update to 3.24.38.

The [patch](https://gitlab.gnome.org/GNOME/gtk/-/commit/7e1a3ffa37abb6d29b2f5216db68c0f362631b05) discussed in the link above however was already included.

**Comment by revvv** [comment]
Looks like that a Ventura update fixed the problem: [GTK issue #5305](url)
@cwscws Can you confirm that?

**Comment by revvv** [comment]
For the record: Apple fixed the problem with Ventura 13.5 to work with GTK 3.24.38.
For now GDash keeps GTK 3.24.36.

AFAIK There are no major bugs fixed (only one warning disappears) and in case someone uses an old Ventura version.
