### ISSUE TITLE
Feature: loop through caveset

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#20]
Press the left key to pass from the first selectable cave to the last selectable cave.
Press the right key to pass from the last selectable cave to the first selectable cave.

**Comment by cwscws** [comment]
I do not fully understand your request. You mean selecting caves in the index by cursor keys?

**Comment by renyxadarox** [comment]
When you load a caveset, you are proposed to play the first cave. If you want to play the 47th cave, you have to press Right 46 times, instead of to press Left 1 time and index on the last (selectable) cave, 47th, if the caveset has 47 caves, for instance.

**Comment by cwscws** [comment]
Can not test at the moment but doesn’t FN or CTrL + left or right the trick?

**Comment by renyxadarox** [comment]
Ctrl is used for Play, so Ctrl+Left or Ctrl+Right definitely don't work.
FN+Left, FN+Right don't work too.
