### ISSUE TITLE
See the entire 40x22 cave

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#21]
If I want to see the entire 40x22 cave on the screen, is it possible to expand the cave view to full screen/window?

Motivation:
I believe a 40x22 cave would be fully visible with a scaling factor of 1 or even 2 on my screen.
I'm forced to set the scaling factor to 5 to make the visible box close to the size of my screen, but all the elements look quite huge with these settings.

**Comment by zsommk** [comment]
In early versions of Gdash this was the case /versions until 2010/, later Cirix eliminated this possibility. All in all, maybe it's a good thing, the current view is similar to that of the commodore 64.

**Comment by zsommk** [comment]
I installed the 2010 version of Gdash to remind myself what it looked like, that is, this large cave view.
And I admit now that as an option it would be an interesting solution.
Could it be done?

**Comment by revvv** [comment]
Where can I get the 2010 version? Or can you make screenshots (game and settings)?

**Comment by zsommk** [comment]
I tried to send you the 2010 version after win, but I got a message that the message is too large .

**Comment by revvv** [comment]
Well then just attach the screenshots here.

**Comment by revvv** [comment]
As a quick solution you can set the visible area here: [GAME_RENDERER_SCREEN_SIZE_X and GAME_RENDERER_SCREEN_SIZE_Y](https://github.com/revvv/gdash-export-CrLi/blob/4752728f92dd5a7eb606183a90431f5b3962815f/src/cave/gamerender.hpp#L45)

The scaling factor still has to be suitable for your monitor.

Unfortunately I don't know how to add this setting yet without ruining the code...

**Comment by cwscws** [comment]
I assume you mean playing a cave without scrolling? Because in the editor you see the full cave on the screen.

But what sense does it make to play the game without scrolling? His would look weird.

**Comment by revvv** [comment]
And it's also some kind of cheating! ;-)

**Comment by renyxadarox** [comment]
Playing the game almost without scrolling:
https://www.youtube.com/watch?v=DPD6NlFFuSQ
Cheating?

**Comment by cwscws** [comment]
Somehow this wouldn’t seem like Boulder Dash anymore for me

**Comment by renyxadarox** [comment]
@cwscws Don't worry, we will keep C64 resolution as default for connoisseurs of the original Boulder Dash. )

**Comment by revvv** [comment]
New release for Windows: Preferences -> Game graphics -> Full screen view

**Comment by zsommk** [comment]
This option has a lot of potential in itself.
In 1920x1080 resolution I normally play on scale 5 and it's ok.
The new option on a scale of 5 or even 4 is unplayable, I can't see Rockford, it's out of view of the monitor.
Only changing the scale to 3 shows me the whole cave.
The idea is good.
On higher scales from 4 onwards, the image should center on the Rockford as in the non-fullscreen version.

**Comment by renyxadarox** [comment]
Just for comparison:
Scroll view:
https://youtu.be/zalm1LKr5ZY
Full cave view (without the title):
https://youtu.be/_fPfWIpQjYM

Playing in full cave view was definitely easier.

**Comment by renyxadarox** [comment]
Some fractional scaling factor is required, to accommodate a header that has 85px height.
For instance, with scaling factor 2.75 a cave 40x22 will occupy 1760x968 and enough space (112px) for a title on a 1920x1080 screen.

**Comment by zsommk** [comment]
At a scale of 4 and above, the cave behaves like "Intermission". Surely on a 2k monitor it will work, but I have to reduce it on a scale of 3.
Question:
The editor has its own scaling level
The Commodore64 style game has a level of scaling,
Can the fullscreen option have its own C64 independent scaling level?

**Comment by cwscws** [comment]
It's interesting to play that way. But Boulder Dash also lives from the unknown lurking around the next screen it scrolls to... ;) So I prefer regular cave view.

**Comment by revvv** [comment]
My last checkin allows now a double value for the scaling factor, so you can use your complete screen.
I had to touch a lot of code, hope I haven't destroyed too much...
The title screen does not like double values... looks odd, so I forced an integer for it. Not sure if there is a better solution.

New release is out.

**Comment by renyxadarox** [comment]
Not bad at all.
Looks good for me with scaling factor 2.9

Just as minor issue, maybe the better step is .125 ?
If the original size of cell is 16x16, the result of scaling with step .125 should always lead to some integer sizes:
1.125 -> 18x18 -> 720x396
1.250 -> 20x20 -> 800x440
1.375 -> 22x22 -> 880x484
1.500 -> 24x24 -> 960x528
...
2.875 -> 46x46 -> 1840x1012
3.000 -> 48x48 -> 1920x1056
and so on.

I don't know, what is a size of header, probably it is also subjected to scaling...

**Comment by zsommk** [comment]
This is now great for the cave test in the editor.
I set the scaling to 2.4 in the editor and in the game in full screen, and ... it's a revelation.
Thank you

**Comment by revvv** [comment]
> Can the fullscreen option have its own C64 independent scaling level?

Yet another scaling level that is only relevant for full screen mode? IMHO we already have enough options.

**Comment by revvv** [comment]
Looks like OpenGL does not like double values: Full screen game is not centered. Right now I don't know how to fix that...

**Comment by renyxadarox** [comment]
It seems to me full screen game was never centered with OpenGL engine, even when there was integer scaling factor.
Try some older GDash-export version with OpenGL engine, scaling factor 1, full screen, the visible area is aligned to left bottom corner. I can make a screenshot, if you want.

**Comment by revvv** [comment]
Oh, good to know. Thought I have something destroyed...

**Comment by renyxadarox** [comment]
The size of app after cold start appropriate to the Scaling factor 5:
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/7180f3e0-6ad2-486b-bb6b-7027dd6361cb)
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/c0a8015e-6bdc-4c40-bf14-6ad68edf71bf)
Make some changes, for example, switch on Particle effects.
The size of application after that becomes appropriate to the "perfect scaling factor for full cave view"
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/b95d55ab-fec3-4faa-9f9d-0495e79b643a)

Each time after app start I am foced to change something in the Settings to adjust app size to the "perfect scaling factor for full cave view".

**Comment by revvv** [comment]
Are you sure you are using the latest version?
Now if you change the "Full cave view" settings the GDash gets restarted. I added the restart flag.

**Comment by renyxadarox** [comment]
Why don't I change the Scaling factor to 2.875 (as a perfect for full cave view)?
Bacuse I am forced to switch off Full cave view and enable full screen mode for recording Intermissions.
A scaling factor for perfect for full cave view is calculated for 40x22 caves and don't change for Intermissions, so the header is fr from Intermission cave, and that is not suitable for video recording:
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/c1945636-7fca-4909-a1c4-b888b701fbe4)
When I turn off Full cave view for Intermission, Scaling factor 5 is good for video recording:
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/549ae67c-beb9-48d8-89ff-c405c3b33a27)

**Comment by renyxadarox** [comment]
> Are you sure you are using the latest version? Now if you change the "Full cave view" setting GDash gets restarted. I added the restart flag.

Yes, GDash gets restarted after changing "Full cave view", it's true, but I say about a cold start.
The preserved scaling factor (5) is used instead of "the perfect scaling factor for full cave view" (2.875) after a cold start.

**Comment by renyxadarox** [comment]
In fact, another inconvenience also appears after the implementation of Full cave view feature:
Every time I run a new cave from the Start screen, the size of app window resizes, so OBS Studio needs some time (~ 2-10 sec) to catch the new window to be able to record it.

I have no idea how to fix it. I understand that window resize is required as a result of Full cave view scaling factor ajustment.
So I'm forced to wait 2-10 sec for OBS Studio catch the window before start a recording.

With "Full cave view" off window size remains the same from the Start screen through all caves, so it's convenient to immediately video recording without interruptions, but then there is no "Full cave view"...

**Comment by revvv** [comment]
Ok, I see that after a cold start there the window size is different compared with right after changing something in the settings.

**Comment by revvv** [comment]
@renyxadarox Thanks for reporting. SDL/OpenGL initalization is different than GTK.
Your OBS concerns:  Yeah, the title screen resolution is a different story. I'm on.
And yes intermissions don't look good in full cave view. I'm on, too.

**Comment by renyxadarox** [comment]
@revvv 
regarding Intermissions and full cave view I see 2 options:

1. calculated optimal scaling factor before each cave start and resize the window. Probably not good case, because there also bypass effect between previous and current caves.
2. align cave header to the top of cave visible area. Something like that:
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/3718a1e4-69d5-4fee-896f-fafc80230b32)

It's not a big deal, to crop video in video editor.

**Comment by revvv** [comment]
Released a new version. Windows seems OK, Mac has problems, but did only a quick test. Therefore marked as pre-release.

**Comment by renyxadarox** [comment]
Looks weird after a cold start, even after the second cold start
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/aa445405-5cfc-4826-a46b-b7add06b49ed)
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/023bdcd1-ee20-4064-831f-e316f1522bb7)
(Full cave view on)

**Comment by revvv** [comment]
Sorry, I messed it up. I fear I can't do more today...

**Comment by renyxadarox** [comment]
I'd rather return back to 1.8.6

**Comment by revvv** [comment]
My problem was I tested with SDL, look find, but OpenGL looks terrible.
Then I always started a game after startup, but if I enter settings immediately you notice a weird font...

So if anybody out there wants to do an endless trial and error session... join me ;-)

**Comment by revvv** [comment]
New release is out. Title screen and cave now have always the same size.

**Comment by renyxadarox** [comment]
@revvv, nice. The OBS issue has been resolved now.

**Comment by revvv** [comment]
Great to hear that.

Unfortunately I was not aware that you can create caves bigger than 40x22. In this case a full cave view makes no sense... I'll try to fix that...

**Comment by cwscws** [comment]
I think the title screen should be enlarged to the window size - otherwise it just looks weird.

**Comment by revvv** [comment]
> I think the title screen should be enlarged to the window size - otherwise it just looks weird.

That's not so easy...

**Comment by renyxadarox** [comment]
Intermissions look very good in Full cave view with Gdashexport-1.9-fork!
@revvv A lot-lot-lot-lot-lot thanks to you for that briliant enhancement!

I have no idea what needs be done to made the Full cave view further better.
I think you can close the issue. Or do you have other ideas of what else can be done?
