### ISSUE TITLE
Magic Wall Timing

### ISSUE THREAD

**Issue by Dustin974** [revvv/gdash-export-CrLi#22]
Hi!
Thanks to the "milling time 0 is infinite" feature, many buggy caves in the \caves folder are now fixed automatically, that's great!

On the other hand, there are also (few) caves which use milling time 0 where it should really mean 0. So in these caves, the magic wall now works too long, making these caves too easy.

I intend to fix these few caves manually. Only 1stB- and CLCK-caves and GDash originals can be concerned, which are not too many, so I should be through the \caves folder relatively quickly. 

I'm going to use the folder in the latest 1.8.1 (win) version for the fix. So, if possible, please don't make any changes in the \caves folder until I'm finished. (1-2 weeks, I guess)

Thanks for your great work improving GDash! 
Dustin

**Comment by revvv** [comment]
You’re welcome! No problem I‘ll wait until you are ready. Take your time!

**Comment by Dustin974** [comment]
That's true! So far, the only caves I fixed were some of my own ones :D I had some ideas for 1-frame milling time here and there.

If I'm not mistaken, the only GDash originals in the \caves folder are my own games, those by \Alchemystics and RTA Dash 8L.

**Comment by cwscws** [comment]
But you CAN use milling time 0 - just deactivate the "milling time 0 is infinite" as this will be saved to the bdcff file and then used correctly.

**Comment by Dustin974** [comment]
I've checked all GDash originals, and it turned out that I'm the only one who used milling time 0 in some caves. So here's my new folder!
(BTW I like it more if the folder is just "Dustin", I think this sounds more personal than with first and last name) :) And I dropped Rock Fort 1 and 2.brc because I made the same games also in .bd for GDash :)

As for the CLCK caves, I was too lazy to check those as well, as they're still relatively many. The only cave I changed here was the known one: CWS BD2, int 2, where I changed the milling time from 0 to 1. Note that a perfect match with the original isn't possible here anyway, because in CLCK the milling timer is synchronized with the cave timer. But 1 is surely closest.
[Dustin.zip](https://github.com/revvv/gdash-export-CrLi/files/12372748/Dustin.zip)
[CWS.zip](https://github.com/revvv/gdash-export-CrLi/files/12372787/CWS.zip)

**Comment by renyxadarox** [comment]
I'm just wondering: should we remove [highscore] from .bd's?

**Comment by renyxadarox** [comment]
Ok, I can remove

**Comment by renyxadarox** [comment]
https://github.com/revvv/gdash-export-CrLi/pull/38 removed [highscore] and [replay]

**Comment by Dustin974** [comment]
> Done. And you want `CWS_Boulder_2.bd` to be deleted? Please confirm.

I wasn't sure about that, but I think it could be deleted. The only difference between both versions is that I changed milling time 0 to 1 in one cave.

**Comment by cwscws** [comment]
.bd can always be deleted after applying a fix. Only .gds should be kept in every case.

**Comment by renyxadarox** [comment]
> .bd can always be deleted after applying a fix. Only .gds should be kept in every case.

Do you mean the opposite?

**Comment by cwscws** [comment]
I meant after fixing/updating a .bd game, you can delete the old, unfixed version. Only .gds files should never be deleted as they are original files from the C64 and may be used in future with a more detailed GDash…

**Comment by renyxadarox** [comment]
Patching .bd should always be done by adding objects, not by editing maps, then the original C64 maps will always be available.
Second, the original .gds can always be retrieved from Github, once it has appeared in a pull pequest.
So I don't see any reason to keep .gds if they need some fix/patch/enhancement.

**Comment by cwscws** [comment]
There is a good reason: there could be objects or settings that are not interpreted fully correct at the moment but maybe with a future version

**Comment by renyxadarox** [comment]
I can repeat: we can retrieve .gds from Github at any moment, even if they have been deleted.
In return, .bd can be enhanced with, for example, a Title Screen, Description, Author, Story, Remark, that .gds never includes.

**Comment by cwscws** [comment]
I would not recommended to store anything for future use outside of the app itself. The .gds files are the true and full Boulder Dash games without any alterations directly from the 8bit computer.

**Comment by cwscws** [comment]
Keep the gds files and combine all 5 level into one bd set. Always keep the gds files in my opinion.
