### ISSUE TITLE
Hide "Snapshot taken" and "Playing Snapshot"

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#23]
Could you please hide
- "Snapshot taken" window after taking a snapshot
- "Playing Snapshot" label in the header after loading a snapshot, 
- intro after loading a snapshot
to make "Take snapshot" and "Revert to snapshot" act as "Quick Save" and "Quick Load" without any annoying interruptions and additions like the ones listed above.

**Comment by zsommk** [comment]
Yes, that's a very good idea.
I wanted to write about that too.
I would also extend it even more, just like in WinVice. In Gdash, after loading the save with the F4 key, the game ends in a given cave, I would like to continue the game.

**Comment by renyxadarox** [comment]
Motivation:
There are a few very difficult caves, which I definitely can't complete without saving.
Taking a snapshot allows to restore the state when the snapshot was taken, but unfortunately the screen looks different.
First of all, because of the inscription "Playing Snapshot". Second, because of the intro after snapshot loading and before playing.
If I want to record a cave walkthrough and combine 2 video pieces, taken before a snapshot and after the last restore, the pieces will look different. So the goal is to restore the game with the same screen view as it was in the moment of snapshoting, with accuracy to the phase of the flap of a butterfly wing. If the goal is not achieved, don't even start changing anything, the functionality of snapshoting is enough for gameplay.
I hope now the motivation to hide also the window "Snapshot taken" is also clear. This spoils the recorded video and fully exposes that the game was played with saves.

P.S.: I get that playing with saves and video editing is a kind of cheating, but who cares?

**Comment by revvv** [comment]
@zsommk
> I would also extend it even more, just like in WinVice. In Gdash, after loading the save with the F4 key, the game ends in a given cave, I would like to continue the game.

I don't understand: "... game ends in a give cave."??

**Comment by zsommk** [comment]
When you use F3 and then F4, the game will end at that cave, there will be no next cave.
Video :

https://www.youtube.com/watch?v=Sxj25i_6gmk

**Comment by zsommk** [comment]
Revelation
The F4 key rewinds time, OK
But it doesn't reset the points earned :(
You can increase your score quickly.
I'm uploading a video
https://www.youtube.com/watch?v=hx3Cdg2-2hA
A very big thank you!

**Comment by revvv** [comment]
Fixed. Before I touched it (1.9.2), the score was just reset.

**Comment by zsommk** [comment]
Bravo to you

**Comment by renyxadarox** [comment]
+1 to bravo!
