### ISSUE TITLE
Feature request: vsync option

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#25]
The fine scrolling works much better than without it but the scrolling is still uneven with slight stutter here on my iMac M1.

Maybe a vsync option (with double/triple buffer?) would help to get real butter smooth scrolling as used to have on a real C64?

On other games/emulators this really helps a lot (at least if it supports 60 Hz - a PAL C64 uses 50.125 Hz so this will never be smooth on my 60 Hz screen).

**Comment by revvv** [comment]
I don't know how to do that, if anybody knows more, just look at the code, we already use: `SDL_GL_SetSwapInterval() / SDL_RENDERER_PRESENTVSYNC`

Isn't this is enough?

**Comment by revvv** [comment]
I dumped the SDL flags using this code snippet [SDL_GetRenderDriverInfo()](https://discourse.libsdl.org/t/sdl-renderer-presentvsync-behaviour/18271/2)
The output on an MacBook Air with Big Sur:
```
Check SDL Window enabled flags:
    SDL_WINDOW_FULLSCREEN    [ ]
    SDL_WINDOW_OPENGL        [X]
    SDL_WINDOW_SHOWN         [X]
    SDL_WINDOW_HIDDEN        [ ]
    SDL_WINDOW_BORDERLESS    [ ]
    SDL_WINDOW_RESIZABLE     [ ]
    SDL_WINDOW_MINIMIZED     [ ]
    SDL_WINDOW_MAXIMIZED     [ ]
    SDL_WINDOW_INPUT_GRABBED [ ]
    SDL_WINDOW_INPUT_FOCUS   [X]
    SDL_WINDOW_MOUSE_FOCUS   [ ]
    SDL_WINDOW_FOREIGN       [ ]

Available 2D rendering drivers:
 0: metal
    SDL_RENDERER_SOFTWARE     [ ]
    SDL_RENDERER_ACCELERATED  [X]
    SDL_RENDERER_PRESENTVSYNC [X]
 1: opengl
    SDL_RENDERER_SOFTWARE     [ ]
    SDL_RENDERER_ACCELERATED  [X]
    SDL_RENDERER_PRESENTVSYNC [X]
 2: opengles2
    SDL_RENDERER_SOFTWARE     [ ]
    SDL_RENDERER_ACCELERATED  [X]
    SDL_RENDERER_PRESENTVSYNC [X]
 3: software
    SDL_RENDERER_SOFTWARE     [X]
    SDL_RENDERER_ACCELERATED  [ ]
    SDL_RENDERER_PRESENTVSYNC [X]
```

Looks like VSYNC is active on macOS. What makes you think, it isn't?

**Comment by revvv** [comment]
To my surprise if I select manually "opengl" as renderer on Windows there is a difference:
1. Scrolling is super smooth with option "fine scrolling"
2. Scrolling is super smooth without option "fine scrolling", but varies in speed??
The only thing that irritates me is that while scrolling the dirt color is darker, but that was the case before, too.

The default renderer is the first which has the requested options: SDL_RENDERER_ACCELERATED and SDL_RENDERER_PRESENTVSYNC. On my Windows this is "direct3d". On Mac I guess it's "metal".

Selecting "opengles2" on Windows produces only a black screen.

Guess I have to add a renderer combo box...

**Comment by revvv** [comment]
Update: Added a checkbox to enable the "opengl" renderer. The other renderers don't seem to change anything or produce a black screen.

By definition the default renderer is the first matching renderer which have: SDL_RENDERER_ACCELERATED and SDL_RENDERER_PRESENTVSYNC, but I don't know how to show the default renderer's name. On my Mac you can only manually select the "opengl" renderer. All other renderes don't work. But there must be another renderer, because the "opengl" renderer has super smooth scrolling and the default one doesn't. I'm confused...

**Comment by cwscws** [comment]
Scrolling is butter smooth with the new option! Wonderful! :)

When switching between display engines by using the editor (as it runs in GTK+) the scrolling in OpenGL slightly stutters again despite the "force OpenGL" option. But this could easily be solved by just pressing F11 when in OpenGL (switching from window to fullscreen mode or vice versa) - then the scrolling is butter smooth again! :)

**Comment by renyxadarox** [comment]
The gameplay is a bit "floaty" with this render on my laptop, I mean there appears a barely perceptible delay between keypress and action, so I tried and went back to the previous render.

**Comment by cwscws** [comment]
I didn’t encounter any delay

**Comment by revvv** [comment]
Please watch out for a log like this:

    M:Renderer: 3=opengl
    M:    SDL_RENDERER_SOFTWARE     [ ]
    M:    SDL_RENDERER_ACCELERATED  [X]
    M:    SDL_RENDERER_PRESENTVSYNC [X]

My Linux laptop for example has never VSYNC, although the quality is a little bit better with "Force OpenGL Renderer".
With `gdash -v` you get even more info like [above](https://github.com/revvv/gdash-export-CrLi/issues/25#issuecomment-1689535367).
