### ISSUE TITLE
Flash effect

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#26]
I noticed that a flash shot in GDash is implemented as an all white screen.
There are several caves, where only a flash shot allows to see something.
I don't know how it looks on C64, but on Atari a flash shot looks like an inversing of foreground color.

As an example, I can show the cave Atari Bandit Boulderdash 16. Cave 20. Bonus Life:
https://youtu.be/tQ-m140zlsk

![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/5b139a08-d07b-4b2c-8bb4-93a97a6e0202)
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/5bf626dc-d52e-4d8e-bc37-d9f27ebd3160)

**Comment by revvv** [comment]
I don’t know what you mean with a flash shot. Maybe if effect that appears after collecting enough diamonds?

**Comment by revvv** [comment]
You want an additional setting like "Outbox open effect" = "Flash" / "Inverted Colors"?

**Comment by renyxadarox** [comment]
I've played one cave in C64 emulator to see what it looks like in it.
It seems to me they also use some kind of inversion of foreground color:
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/51cf3b83-4df7-4539-8731-582fbb376c5a)
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/8910a408-c383-4876-accf-b830b75501f8)

Actually, "Color Inversion" should not be taken literally.
It looks like:
1) inverse the color of all areas with the background color
2) change the color of all other areas to the color of dirt (Color 1)
You can correct me if I'm wrong.

Answering your question, I prefer to change flash effect without any additional settings.
Just becuase it seems to me all white screen is not an implementation of the original C64 flash effect, so I don't see any reason to keep it.

**Comment by renyxadarox** [comment]
Actually, I see I was wrong, everything is a little more complicated.
Color inversion won't help us with the 1st cave I mentioned, 'cause all the black areas will be inverted to white and we won't achieve the goal.
We should have an algorithm for how each element of the cave should look during the flash effect.
What I mean is that all colors of element's ordinary view need to be changed to either the inverted background color or the dirt color.

**Comment by cwscws** [comment]
I think only the background color flashes to white. This should result in seeing the cave.

**Comment by renyxadarox** [comment]
@cwscws there are many such kind caves. From the last I remember:
GDash Nahost 91. Intermission 26: https://youtu.be/DZOwsrFz8EA
GDash Alex Zop. Cave 08: https://youtu.be/xm10rNp-JwY
GDash Alex Zop. Cave 04: https://youtu.be/jU2S3MVaNQM
The 2nd one is very intersing that background color is white and it should change to black, making all other stuff very constrast during the flash.

**Comment by cwscws** [comment]
What if you record such caves with a higher frame rate and have a closer look with your video editing software what happens during that flash.

**Comment by renyxadarox** [comment]
I've already explained above my vision what happens during the flash:
All colors of all element's ordinary view need to be changed to either the inverted background color or the dirt color.
For instance, all Rockford's view stages during 5 frames, while flash continues, looks as:
1.
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/48c1d832-ffd2-4085-b7f6-49c9cbfa8091)
2-3.
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/936864c7-bb69-4565-b303-ca79f13db1c7)
4-5.
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/10e3882d-e721-481b-b07b-d1387a5ddfa7)

Black is the dirt color (Color 1), yellow could be replaced by the inverted background color -- white:
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/ad0a054d-e738-4210-84d1-2e2019325b69)

The ordinary element's view colors doesn't depend on cave colors, so, in fact, there are two possible ways, how the "inverted" element view could be generated: in-flight or pre-prepared. In-flight meens to take the ordinary element's view and convert all element colors to the dirt color, all backgound color -- to the inverted color, per each frame during the flash effect. Pre-prepared means that the view of all stages of all elements present in the cave could be prepared and cached even before the cave game started.
Since there's a story of Save/Load game snapshot, in-flight approach is preferable, IMHO.

**Comment by renyxadarox** [comment]
Another yet absolutely black cave:
[caves/Boulder_Rush_cave_pack/Thomas_Richter.gds](https://github.com/revvv/gdash-export-CrLi/blob/master/caves/Boulder_Rush_cave_pack/Thomas_Richter.gds) **Cave 07**
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/1bc7b5bc-f1da-4aae-a683-60a00cc1f603)
After flashing it could look like that:
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/2c231a2a-4d24-43bf-b799-f27e12fa31d8)

**Comment by revvv** [comment]
Tried to change the color flash effect. Don't know why a color update has no effect. I'm something missing...

**Comment by revvv** [comment]
Had no time to dig deeper. I still don't understand how the flash effect currently works.
But to use arbitrary colors you would need to rework the code a lot. It's currently not possible to change the colors when completing a cave.

And F2 changes randomly the colors  (Some kind of cheat for dark caves)
