### ISSUE TITLE
Question: load Atari emulator memory snapshots

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#27]
I have found in po that GDash is able to load levels from Atari emulator memory snapshots.

> #: src/misc/helptext.cpp:77
msgid ""
"The game comes with many built-in and pre-installed cave sets, and you can "
"also make up your own levels. Just use the options in the title screen. You "
"can load caves stored in the BDCFF format, but GDash is able to load levels "
"from C64 and Atari emulator memory snapshots as well."

Could somebody explain how to do this?
Or was this functionality eliminated at some moment, leaving the rudiments of it in the helptext?

If this functionality really exists, I have an idea to convert some Atari Boulder Dash clones, that are not present in GDash, to GDash cavesets.

**Comment by revvv** [comment]
Never tried myself, but @cwscws told me it works for C64 dumps:

    $ gdash in.vsf --save-gds out.gds -q

@cwscws told me it does not produce log messages, so he prefers `any2gdash`, which I also never used.

**Comment by renyxadarox** [comment]
Ok, very good.

The original gdash-20130427unstable says me what to do, there appeared a file stderr after some attempt to run

```
$ gdash in.vsf --save-gds out.gds -q
```

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Memory map file should be 65536+2 bytes long or 65536 bytes long. Use save "filename" 0 0000 ffff in vice monitor. Use write 0000 ffff filename in atari800 monitor.
```

So, I used Atari800Win monitor for memory dump:
```
write 0000 ffff bobo1
```
After that I was able to convert it using gdash-20130427unstable and gdash-export as well:
```
$ gdash bobo1 --save-gds Bobo1.gds -q
```
After that I opened it in the GDash Cave Editor and made some changes: added info about author, renamed caves.
After that I saved it in BDCFF format as Bobo1.bd and tried to Export CrLi cave pack as GDash_Bobo1.gds.
After that the file in BDCFF format Bobo1.bd is loaded successfully. But I got a message "Cannot determine file format" on try to load GDash_Bobo1.gds saved by "Export CrLi cave pack".
[Bobo1.zip](https://github.com/revvv/gdash-export-CrLi/files/12312570/Bobo1.zip)

What am I doing wrong?

**Comment by renyxadarox** [comment]
Ok, how can I make some changes and save the caveset back as gds?

**Comment by renyxadarox** [comment]
```
gdash Bobo1.bd --save-gds GDash_Bobo1.gds
```
does nothing

**Comment by renyxadarox** [comment]
Hmm, in this case how @Dustin974 is going to fix caves ( #22 ) ?
The fix will result in gds, right?

**Comment by renyxadarox** [comment]
Ok, @revvv , are you interested in getting cavesets from Atari Boulder Dash clones, that aren't in GDash?
If yes, what format should they be? gds as a result of gdash --save-gds or BDCFF as a result of editing gds?
Maybe there are / should be some naming conventions, for example we need to add Atari_ as a prefix to all cavesets?
What can be the result of my activity? Would you like a ZIP with .db sorted in directories by authors?

I thought to minimize your efforts of adding new cavesets to GDash caves... but if the feature of export to gds is not implemented... we have to come to some agreement before I begin.

**Comment by revvv** [comment]
Sure, I'm interested. I personally prefer BDCFF, but I see there are already a lot of caves in both formats. I don't know the reason, but maybe the BDCFF was modified to be compatible with GDash?

You can give me a ZIP file or do a PR whatever you like...

A prefix sounds reasonable.

**Comment by renyxadarox** [comment]
Successfully imported cavesets:
../caves/Bobosoft/Bobo1_Atari.bd
../caves/Bobosoft/Bobo3_Atari.bd
../caves/Bobosoft/Bobo4_Atari.bd
../caves/Max/Max1.bd -- from C64
../caves/Max/Max2.bd -- from C64
../caves/Persoft/HOP_1_Atari.bd
../caves/Persoft/HOP_2_Atari.bd
../caves/Persoft/HOP_3_Atari.bd
../caves/Persoft/HOP_4_Atari.bd
../caves/Iron_Soft/Iron_Soft_1_Atari.gds == ../caves/various/Boulder_Dash_9.gds
../caves/Iron_Soft/Iron_Soft_2_Atari.gds == ?
../caves/Iron_Soft/Iron_Soft_3_Atari.gds == ../caves/various/Boulder_Dash_5_Artur_Losinski.gds
../caves/Iron_Soft/Iron_Soft_4_Atari.gds == ?
../caves/LTL_Soft/LTL_Soft_1_Atari.bd
../caves/LTL_Soft/LTL_Soft_2_Atari.bd
../caves/Mapasoft/Mapasoft_Atari.gds == ../caves/various/Boulder_Dash_11.gds
../caves/various/Boulder_Dash_8_Atari.gds == ../caves/various/Boulder_Dash_8_Artur_Losinski.gds
../caves/various/Boulder_Dash_20_Atari.bd
../caves/Scserbin_Zoltan/Boulder_Dash_Bee_001_Atari.bd
../caves/Scserbin_Zoltan/Boulder_Dash_Birds_001_Atari.bd
../caves/Scserbin_Zoltan/Boulder_Dash_Dig_Dug_001_Atari.bd
../caves/Scserbin_Zoltan/Boulder_Dash_Fire_Ant_001_Atari.bd
../caves/Scserbin_Zoltan/Boulder_Dash_Ninja_001_Atari.bd
../caves/Scserbin_Zoltan/Boulder_Dash_Pacman_001_Atari.bd
../caves/various/Dotter_Dash_07_Atari.bd
../caves/Alex_Zop/Rocki_im_Lolliland_Atari.bd
../caves/various/Walace_Glazy_Atari.gds

btw
../caves/Marc_Pierau/Rockford_in_Nimmerland_2.gds belongs to Alex_Zop

Unfortunately could not import the next Atari memory dumps:
 -- Could not import cave data -- unknown cave format!

- Boulder_Dash_a_la_JD
- Boulderdan_1
- Boulderdan_2
- BSM_Boulder_Dash
- Kendallsoft_Kaverns
- Lighting_Dash
- Boulder_Dash_+1
- Boulder_Dash_+2
- Boulder_Dash_+3
- Boulder_Dash_+4
- Cuevas_Dr_Mugen_1
- Cuevas_Dr_Mugen_2
- Cuevas_Dr_Mugen_3
- Cuevas_Dr_Mugen_4
- Cuevas_Dr_Mugen_4_First_Edition
- Cuevas_Dr_Mugen_4_Second_Edition
- Cuevas_Dr_Mugen_4_Third_Edition
- Cuevas_Dr_Mugen_5
- Cuevas_Dr_Mugen_6
- Cuevas_Dr_Mugen_7
- Cuevas_Dr_Mugen_8
- Cuevas_Dr_Mugen_9
- Cuevas_Dr_Mugen_10
- Cuevas_Dr_Mugen_11
- Cuevas_Dr_Mugen_11B
- Cuevas_Dr_Mugen_12
- Cuevas_Dr_Mugen_13
- Cuevas_Dr_Mugen_14
- Cuevas_Dr_Mugen_15
- Cuevas_Dr_Mugen_16
- Cuevas_Dr_Mugen_17
- Boulderdash_Mugen_18
- Cuevas_Dr_Mugen_19
- Cuevas_Dr_Mugen_20
- Cuevas_Dr_Mugen_21
- Mugen_Challenger
- Dr Mugen Extra Caves

**Comment by cwscws** [comment]
GREAT! :)

You forgot to add _Atari to Max1.bd and Max2.bd

Can you include the missing Atari Boulder Dashes which can not be converted as memory dumps AND the original Atari files (to load on an emulator) to the caves.zip file?

**Comment by renyxadarox** [comment]
I didn't forget to add _Atari to Max1.bd and Max2.bd because I could not import them from Atari memory dumps, but I found the same games for C64 and converted them from VICE memory dump. So I decided do not add "_C64".

> Can you include the missing Atari Boulder Dashes which can not be converted as memory dumps AND the original Atari files (to load on an emulator) to the caves.zip file?

Yes, sure, but as a separate file.

**Comment by renyxadarox** [comment]
@cwscws 
[atari.zip](https://github.com/revvv/gdash-export-CrLi/files/12320242/atari.zip)

**Comment by cwscws** [comment]
Thanx!

**Comment by renyxadarox** [comment]
..caves/Scserbin_Zoltan/Atlantis_25.gds == ..caves/Firefox/Firefox_01.gds
..caves/Scserbin_Zoltan/Atlantis_27.gds == ..caves/Firefox/Firefox_03.gds
..caves/Scserbin_Zoltan/Atlantis_28.gds == ..caves/Firefox/Firefox_04.gds
..caves/Scserbin_Zoltan/Atlantis_29.gds == ..caves/Firefox/Firefox_05.gds
..caves/Scserbin_Zoltan/Atlantis_30.gds == ..caves/Firefox/Firefox_06.gds
..caves/Scserbin_Zoltan/Atlantis_31.gds == ..caves/Firefox/Firefox_07.gds
..caves/Scserbin_Zoltan/Atlantis_32.gds == ..caves/Firefox/Firefox_08.gds
..caves/Scserbin_Zoltan/Atlantis_33.gds == ..caves/Firefox/Firefox_09.gds
..caves/Scserbin_Zoltan/Atlantis_35.gds == ..caves/Firefox/Firefox_11.gds
..caves/Scserbin_Zoltan/Atlantis_36.gds == ..caves/Firefox/Firefox_12.gds
..caves/Scserbin_Zoltan/Atlantis_37.gds == ..caves/Firefox/Firefox_13.gds
..caves/Scserbin_Zoltan/Atlantis_38.gds == ..caves/Firefox/Firefox_14.gds
..caves/Scserbin_Zoltan/Atlantis_39.gds == ..caves/Firefox/Firefox_15.gds
..caves/Scserbin_Zoltan/Atlantis_40.gds == ..caves/Firefox/Firefox_16.gds
..caves/Scserbin_Zoltan/Atlantis_41.gds == ..caves/Firefox/Firefox_17.gds
..caves/Scserbin_Zoltan/Atlantis_42.gds == ..caves/Firefox/Firefox_18.gds
..caves/Scserbin_Zoltan/Atlantis_43.gds == ..caves/Firefox/Firefox_19.gds
..caves/Scserbin_Zoltan/Atlantis_44.gds == ..caves/Firefox/Firefox_20.gds
..caves/Scserbin_Zoltan/Atlantis_45.gds == ..caves/Firefox/Firefox_21.gds
..caves/Scserbin_Zoltan/Atlantis_46.gds == ..caves/Firefox/Firefox_22.gds
..caves/Scserbin_Zoltan/Atlantis_47.gds == ..caves/Firefox/Firefox_23.gds
..caves/Scserbin_Zoltan/Atlantis_48.gds == ..caves/Firefox/Firefox_24.gds
..caves/Scserbin_Zoltan/Atlantis_49.gds == ..caves/Firefox/Firefox_25.gds
..caves/Scserbin_Zoltan/Atlantis_50.gds == ..caves/Firefox/Firefox_26.gds
..caves/Scserbin_Zoltan/Atlantis_51.gds == ..caves/Firefox/Firefox_27.gds
..caves/Scserbin_Zoltan/Atlantis_52.gds == ..caves/Firefox/Firefox_28.gds
..caves/Scserbin_Zoltan/Atlantis_53.gds == ..caves/Firefox/Firefox_29.gds
..caves/Scserbin_Zoltan/Atlantis_54.gds == ..caves/Firefox/Firefox_30.gds
..caves/Scserbin_Zoltan/Atlantis_55.gds == ..caves/Firefox/Firefox_31.gds

..caves/Scserbin_Zoltan/Dig_Dug_Dash_07.gds == ..caves/Prof_Knibble/Knibble_Dash_7.gds

..caves/Scserbin_Zoltan/Batman35.gds == ..caves/Scserbin_Zoltan/Batman36.gds

**Comment by renyxadarox** [comment]
Many-many-many-many-many-many-many changes, I did.
Added many new cavesets exported from C64, reviewed and catalogued exisiting.

remote: Permission to revvv/gdash-export-CrLi.git denied to renyxadarox.
So I just add caves catalogue as a zip for complete replacement.

[caves.zip](https://github.com/revvv/gdash-export-CrLi/files/12325072/caves.zip)

**Comment by cwscws** [comment]
Please coordinate your work with Dustin - he is updating and correcting the caves folder!

**Comment by renyxadarox** [comment]
I don't know how to coordinate my work with Dustin, I have no permissions to create a new branch in this project.
All I can, I can just upload files. Do I have to wait for Dustin to make changes and update the caves folder after that? Ok, I will.

**Comment by revvv** [comment]
I just had no time to have a look at your work. And you don't need write permission, just make a PR or wait until I check it in...
Thank you for the new caves!

**Comment by renyxadarox** [comment]
@revvv Ok, I got it. There exists an opportunity to create PR based not only on comparison of two branches, but also across two forks. Nice.

https://github.com/revvv/gdash-export-CrLi/pull/28

**Comment by cwscws** [comment]
I would recommend to put all official Boulder Dashes into a "FirstStarSoftware" folder and not a "Peter_Liepa" folder.

**Comment by revvv** [comment]
Had to rename `The_Bremer_Town-Musicus `to `The_Bremer_Town_Musicus`. A dash `-` is not allowed in variable names in Makefiles.

**Comment by renyxadarox** [comment]
What about files? Is `-` allowed in file names?

**Comment by revvv** [comment]
Yes, that's ok.

**Comment by renyxadarox** [comment]
mea culpa, @revvv thanks
