### ISSUE TITLE
OpenGL full screen not centered

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#29]
When pressing F11 to switch to full screen, the screen is not centered in OpenGL in MacOS (displayed on the left side instead of centered). It is centered in SDL and GTK+.

**Comment by revvv** [comment]
This happens also on Windows. It started occurring with my first fork release.
Last official GDash correctly centered OpenGL, but there were a lot of code changes by Zoltan and many 3rd party library updates.
I'd love to fix this, even more it would improve the "full cave view" I'm still working on.

I guess it has something to do with `glViewport()` and `glOrtho()`.

**Comment by revvv** [comment]
If I remove `glViewport()` completely the game is centered in fullscreen, but also looks like it was stretched.

**Comment by cwscws** [comment]
Stretched is not good, aspect ratio should be correct.

**Comment by revvv** [comment]
Can you tell my why full screen size on Windows/Linux stretches the graphics to fit the screen, while on Mac it is not stretched, but just adds black areas around the graphics?

So my approach would be:
1. Add new setting "Center OpenGL full screen"
2. Ignore user scaling factor, use calculated one. Don't call `glViewport()` to get centered.
3. The game gets scaled preserving the aspect ratio.
4. Find out why intermissions are scaled differently and not preserving the aspect ratio. Have you noticed the missing pixel line at the top and the bottom?

**Comment by cwscws** [comment]
That’s one of the mysteries that would really be interesting to know😎

Black bars should be only left and right, or did I misunderstand something?

**Comment by cwscws** [comment]
I just read the manual of glViewport. As far as I understand this, the initial values are 0,0 for the lower left corner - which would explain why it’s not centered.

**Comment by revvv** [comment]
> I just read the manual of glViewport. As far as I understand this, the initial values are 0,0 for the lower left corner - which would explain why it’s not centered.

It's just the start coordinate. The full screen flag should just do what it says... But why the hell does it work on Linux and not Windows/Mac?

**Comment by revvv** [comment]
New release is out. Let me know what you think. Note that the user defined scaling factor is relevant.

**Comment by cwscws** [comment]
Generally a good workaround! But I’m not fully happy with the slightly stretched screen as there are more visual distortions when using shaders like crt-geom so a correct aspect ratio would be nicer (with black bars left and right on a 16:9 display). But at least this option can be switched on/off…😎

**Comment by renyxadarox** [comment]
There are a small repeatable bug:

1. Go to Options and set
- Scaling factor: 5
- Full cave view: yes
- OpenGL: Center full screen: no

3. Play a full screen game. Visual area aligns left as expected
4. Go to Options and set:

- Full cave view: no

5. Play a game. Everything looks as usual
6. Go to Options and set:

- Full cave view: yes

7. A new game starts on centered screen
8. Switching "OpenGL: Center full screen: no/yes" doesn't affect the result: every new full screen game starts on centered screen and only cold start of GDash helps.

Not a big deal, just a minor issue.

**Comment by renyxadarox** [comment]
To be honest, I would rather always have a cantered full screen and an option to stretch a visual area to bounds (which may causes visual distortions) or do not stratch and have a precise visual area aspect ratio (with black bars left and right).
But if this is difficult to implement for some reason, the current version's solution is also a pretty good workaround.

**Comment by revvv** [comment]
@renyxadarox wrote
> There are a small repeatable bug
> [...]
>  every new full screen game starts on centered screen and only cold start of GDash helps.

I could reproduce it on Windows. IMHO this is an OpenGL bug or feature. I guess that it's not centered at the beginning is the bug. My setting just adds a workaround...

**Comment by renyxadarox** [comment]
>I guess that it's not centered at the beginning is the bug. My setting just adds a workaround...
Does it make sense to have the option "OpenGL: Center full screen" at all?
In my opinion, few people need to have full screen left alignment.
Most people would be happy with always centered full screen.

Actually, no matter what is a value of "OpenGL: Center full screen" option, the full screen view is always centered now and it affects only visual area aspect ratio:

OpenGL: Center full screen: **no**
1680x1050
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/c927897c-ae35-4197-a952-ddc7ee46018c)

OpenGL: Center full screen: **yes**
1680x1050
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/bff5ceaf-e1e1-4bca-8ad4-d37d5a03b0f2)

So, maybe you should rename it as "Full screen: Stretch to bounds"? Because that's exactly what it's doing right now.
In Windows at least. Maybe this option works differently in McOS, I don't know.

**Comment by cwscws** [comment]
Maybe Czirkos Zoltan can help?

Or maybe there are websites where these things could be asked? I’m no programmer unfortunately…

**Comment by revvv** [comment]
I have updated SDL: mingw-w64-x86_64-SDL2 2.26.5-1 -> 2.28.2-1
No change. That's all I can do for now.

**Comment by revvv** [comment]
To preserve the aspect ratio you need to set a higher scaling factor. Forgot to mention that.

**Comment by revvv** [comment]
Now I know that this happens on all platforms and if it happens depends on the screen size.
I'm going to calculate the perfect scaling factor.  SDL will add only one small black bar somewhere, but this preserves the aspect ratio.
Enabling the setting `opengl_center` will stretch the image almost unnoticeable. So maybe we can remove the setting completely and preserve the aspect ratio.

**Comment by revvv** [comment]
I though I have fixed it, now my Linux laptop does cut off the score for 40x22 view. (Release 1.9.5)
I have checked when this happens with `gdash -v`: (Tried different view sizes)
Values for `h_padding` that work correctly: 70, 132
Values for `h_padding` that don't work correctly: 245, 210, 160

So the conclusion is: Whenever `h_padding` is at least 160 it is a problem??
