### ISSUE TITLE
Mac: Crash in Editor / Test Cave

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#3]
Here on my M1 GDash crashed in the Editor when selecting Test Cave and then pressing F1 to leave the test

**Comment by revvv** [comment]
I can confirm this occurs on Mac OS 11.7.7 (Big Sur): signal 11. I'm a little bit surprised that I haven't noticed it. Maybe it works on my dev Mac OS 10.15.7 (Catalina)...

**Comment by cwscws** [comment]
Using Ventura on my M1 :)
