### ISSUE TITLE
Editor: Add Outboxes to Elements statistics

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#31]
Sometimes there exists failure cave with no Exits.
If to add Outboxes + Invisible Outboxes to Cave Elements statistics, it will be easier to determine the failure.

Maybe, as a proposal, to change the way how Cave Elements statistics is calculated: to dynamically populate the list with all items present in the cave.

![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/2bc40278-443e-42bf-a9c0-c010df642730)
14 + 416 + 210 + 37 + 3 + 12 = 692
880 - 692 = 188.
What are these 188 unknown elements?
Who is interested to know that Alternative fireflies, Alternative butterflies, Stoneflies and Amoebas are absent there?
I'm interested to know, where is an exit, Lebowski? )

**Comment by revvv** [comment]
Now all elements appear in the statistics and the sum should be correct, too.
All elements with same name only appear once. Like fireflies with different directions.
Numbered elements like "Dirt" and "Dirt 2" appear separately.
