### ISSUE TITLE
Cave selector goes astray

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#34]
Cave selector goes astray after changing Game graphics options.
As an example:
/caves/American_Action/Boulder_Dash_3
Cave: L. palya/2 goes Cave: A. palya/1
after turning Full cave view on or off, or changing the scaling factor to a different value.

**Comment by revvv** [comment]
Some settings trigger a restart of GDash. Many settings are lost. Even the game you are playing is gone for good.

**Comment by renyxadarox** [comment]
Does it make sense to fix it?

**Comment by revvv** [comment]
It would require to save the cave number to the gdash.ini file and after restart to restore the value. IHMO it's not worth the effort.

**Comment by cwscws** [comment]
That’s certainly true - but all that efforts only for recording videos is a little bit exaggerated…

**Comment by renyxadarox** [comment]
I asked "Does it make sense to fix it?"
@revvv answered "IHMO it's not worth the effort"
If he answered "It is a little bit exaggerated", I would say "Ok, (wontfix)"

So what do you want from me?
Do you want to change my opinion, what is important for me? You won't be able to.

**Comment by cwscws** [comment]
No offense. If it is only inconvenient for video recording but the game itself works as intended, thats no big deal in my opinion.
