### ISSUE TITLE
Alchemyst Dig 02 is the wrong version

### ISSUE THREAD

**Issue by thealtermaven** [revvv/gdash-export-CrLi#36]
The current version of Alchemyst Dig 2 that is supplied as a GDash caveset is out of date. The newest version, 13 May 2021, fixed a bug in Cave IV (start 2). Please pull my current release under /BDCFF-sets, all caves present are the most recent caves.

**Comment by renyxadarox** [comment]
https://github.com/revvv/gdash-export-CrLi/pull/35/commits/80b2d829bc006c991abc6d36573cfe6a1b361123

**Comment by thealtermaven** [comment]
Thank you. This is the update.
