### ISSUE TITLE
Question: What makes GDash think a caveset is multilevel?

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#37]
What makes GDash think the [/caves/Arno_Weber/Future_Dash.bd](https://github.com/revvv/gdash-export-CrLi/blob/master/caves/Arno_Weber/Future_Dash.bd) is multilevel?

**Comment by revvv** [comment]
What is a multilevel?

**Comment by renyxadarox** [comment]
Multilevel means that GDash thinks that a caveset has 5 levels and add /{level} to cave name:
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/46683531-04fa-46ca-93d7-8ac7168118db)

**Comment by revvv** [comment]
It the depends on the height of the title screen, how many lines with cave infos are added: [titlescreenactivity.cpp](https://github.com/revvv/gdash-export-CrLi/blob/8c185ca132f7471dc85743d8693e946ac9bf4ce7/src/framework/titlescreenactivity.cpp#L94)

**Comment by renyxadarox** [comment]
Excuse me, @revvv I didn't understand your answer.
Why GDash think the [/caves/Arno_Weber/Future_Dash.bd](https://github.com/revvv/gdash-export-CrLi/blob/master/caves/Arno_Weber/Future_Dash.bd) is multilevel
and [/caves/Arno_Weber/Exploding_Dash.bd](https://github.com/revvv/gdash-export-CrLi/blob/master/caves/Arno_Weber/Exploding_Dash.bd) is not?
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/566c8e9f-5792-4b64-8b60-1a1c040aab82)
What difference between two these cavesets?

**Comment by renyxadarox** [comment]
Actually I was asking about
`caveset_has_levels = app->caveset->has_levels();`
How GDash defines that caveset has levels?
In my opinion [/caves/Arno_Weber/Future_Dash.bd](https://github.com/revvv/gdash-export-CrLi/blob/master/caves/Arno_Weber/Future_Dash.bd) has no levels, but something makes GDash think that it has.

**Comment by revvv** [comment]
Sorry, this was a misunderstanding. Future Dash Cave 14 has different AmoebaThreshold values...
It was probably me, to make it playable, but I (always) only fix level 1. I thought this was a good idea, so I can see what the original value was... bad idea... fixed...
