### ISSUE TITLE
Feature request: New animation running up and down

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#4]
would it be possible to implement a new animation for running up and down?

Asked Cirix several times in the last few years but he always refuses to continue working on GDash…

![6B9AC71F-81D9-45F7-B35A-590038FF9F1A](https://github.com/revvv/gdash-export-CrLi/assets/5362135/ff0b4db7-67dc-4070-9e0f-8b24252ddb35)

**Comment by revvv** [comment]
I saw this kind of animation somewhere, but I forgot which BD engine it was.. do you know more?

**Comment by cwscws** [comment]
This was an idea of the user Retrofan in forum64.de.

Here is the thread:
https://www.forum64.de/index.php?thread/80814-boulder-dash-c64-typisch-vs-atari-800-optik/&pageNo=1

**Comment by revvv** [comment]
I swear I played a BD clone which had this new animation, but I can't remember which one...

**Comment by cwscws** [comment]
Can’t imagine as this was only a demonstration animation but who knows

**Comment by cwscws** [comment]
Btw this is only the animation for running downwards. When running upwards only the eyes couldn’t be seen (obviously)😎

**Comment by cwscws** [comment]
Made the animation phases already

https://github.com/revvv/gdash-export-CrLi/assets/5362135/ff759d40-e72f-45f9-9b1d-2793dd7c6781


https://github.com/revvv/gdash-export-CrLi/assets/5362135/8a52b98a-5579-41dc-9918-99ed3efd2ef3
