### ISSUE TITLE
Wrong direction of the butterfly

### ISSUE THREAD

**Issue by zsommk** [revvv/gdash-export-CrLi#40]
I noticed it only today, I played Brain_Delicacy_Dr_Guru
I see some anomaly.

It is not available in version 1.1 yet.
It has been available since version 1.2.
Here is a short video from version 1.1 and later.

good version  https://www.youtube.com/watch?v=mWtaogYEau8

Wrong version  https://www.youtube.com/watch?v=uEN2PJ-uVoc

**Comment by revvv** [comment]
Hm... Once upon a time I noticed that exporting to CrLi resulted in butterflies with wrong directions...
So I "fixed" it: [f2c9913](https://github.com/revvv/gdash-export-CrLi/commit/f2c9913cfdc84fc8a0e519cf547e35d6d3d70fca)
IIRC I asked Zoltan, but he said that he's not using exported CrLi files.

And in the C64 original the bufferly behaves correctly?
And thanks for narrowing down the problem!

**Comment by zsommk** [comment]
Yes, under C64 as well as in all older versions of Gdash it is correct.
Only those from version 1.2 and later have a problem.

**Comment by renyxadarox** [comment]
@revvv convert gds to db and change the butterfly orientation

**Comment by revvv** [comment]
@renyxadarox Yes, that's probably what I'm going to do, but could someone confirm that my understanding of the spec is correct?

I did these tests:
- Test 1
    - GDash: Create a cave with all butterflies, export to CrLi
    - CLCK: Load cave. Butterflies work as expected.
- Test 2
    - CLCK: Create cave with all butterflies, create game, load game, save snapshot
    - GDash: Import snapshot.vsf

All tests were successful.

**Comment by revvv** [comment]
Converted all  GDashCRL .gds caves: [fd65fb6](https://github.com/revvv/gdash-export-CrLi/commit/fd65fb648bf06b14e1a3f0407fd2bedea820ad19)

**Comment by zsommk** [comment]
Thank you for manually making changes to these gds files.

However, if someone takes a memory dump from the winvice emulator to the vsf file and wants to play Gdash in this way, wanting to feel the C64 version, he will consider that this cave is impossible to pass.

I appreciate what you do for Gdash.
You have brought a lot of healings to this game.
Sam regrets that I do not know programming so that we can patch the game together.
Stay with us (fans) of Boulderdash as long as possible.
