### ISSUE TITLE
Additional FireFox games

### ISSUE THREAD

**Issue by zsommk** [revvv/gdash-export-CrLi#43]
I found it on www.lemon64.com
four Firefox games missing from Gdash.

I upload them as core dumps from WinVice to the vsf file.
These are:
Firefox57
000 Whitedash
001 Yellowdash
002 Orange dash
[FireFox.zip](https://github.com/revvv/gdash-export-CrLi/files/12435852/FireFox.zip)

**Comment by zsommk** [comment]
By the way.
At https://wowroms.com/
you can find missing No_One games
13,14,15,28,29,32,33,34,35,36,37
Unfortunately, I couldn't find 38.39 anywhere

I pass them in vsf file format
[no1.zip](https://github.com/revvv/gdash-export-CrLi/files/12436245/no1.zip)

**Comment by renyxadarox** [comment]
Unfortunately I cann't open your vcf's. Says:
"Magic string mismatch in snapshot"
But I could try to extract cavesets from the games directly, if you give the direct links to ROMs.

P.S.: I've already found White Dash and managed to convert it to gds.

**Comment by zsommk** [comment]
hmm..
Gdash reads WinVice dump snapshots without any problems.
All right.
I am sending the same games on D64 floppy disks
[pack.zip](https://github.com/revvv/gdash-export-CrLi/files/12436397/pack.zip)

**Comment by renyxadarox** [comment]
hmm...
I have never before tried to open vsf by GDash.
It worked.

**Comment by zsommk** [comment]
CWS.
I congratulate you on the release of the third game of your series.

**Comment by renyxadarox** [comment]
@zsommk I've got them all.
https://github.com/revvv/gdash-export-CrLi/pull/44 Additional FireFox and No One's games

**Comment by zsommk** [comment]
OK. Thank you.

**Comment by renyxadarox** [comment]
BTW,
/caves/No_One/No_One_s_Boulder_32.gds == /caves/The_Blockheads/Boulderdash_32.gds
/caves/No_One/No_One_s_Boulder_33.gds == /caves/The_Blockheads/Boulderdash_33.gds
/caves/No_One/No_One_s_Boulder_37.gds == /caves/The_Blockheads/Boulderdash_37.gds
/caves/No_One/No_One_Boulder_Head_06.gds == /caves/The_Blockheads/Boulderhead_6.gds

So, it's very possible that the maps from No One Boulder 38 and 39, you can't find, are the same as
/caves/The_Blockheads/Boulderdash_38.gds
/caves/The_Blockheads/Boulderdash_39.gds
which we already have.

**Comment by zsommk** [comment]
That would explain a lot.
On the website https://csdb.dk/
there is information:

The Blockheads (TBH)
AKA:
Blockheads Distribution Company BDC B.D.C.

group type :
Fixing Group

Base Country :
Netherlands

User rating: awaiting 8 votes (8 left)

All Members :
No One (ex) .... Coder, Cracker, Hacker

Which means No One is a member of the group.

**Comment by cwscws** [comment]
Here is my full C64 Boulder Dash collection - maybe there are games included that are still missing in GDash?

https://www.dropbox.com/scl/fi/zvb5s8ql8ou77chv5b4ja/BoulderDashCollectionC64.zip?rlkey=3be4157nj59g3tbcci8zsoh81&dl=0

**Comment by renyxadarox** [comment]
> Here is my full C64 Boulder Dash collection - maybe there are games included that are still missing in GDash?
> 
> https://www.dropbox.com/scl/fi/zvb5s8ql8ou77chv5b4ja/BoulderDashCollectionC64.zip?rlkey=3be4157nj59g3tbcci8zsoh81&dl=0

Thanks. 
I was able to open&extract&convert the following missing cavesets:
- Add & TKR Boulder Pack A - E
- Artis Boulder Dash Caves
- BlockHeads Boulder Head 7
- BlockHeads Boulder Head 8
- Boulder Dash The Lost Caves 11
- Boulder Dash The Lost Caves 12
- Boulder Dash The Lost Caves 13
- Boulder Dash Cribble
- CS Boulder 2
- DiamondRush 1 - 5
- Exotic Boulder Dash 1
- Boulder Dash Expert 1 - 3
- RSD Boulder Dash
- Final Game 1 - 6
- NoOne Final Boulderdash
- NoOne Surprise Boulder
- NoOne Work Boulder
- Rockford Elf Boulder Dash Games
- Rockford Profi Boulder 20, 21
- Rockford True Boulder 1
- Ron Van Schaik Dash 15
- Ron Van Schaik Dash 16
- Super Dash One
- KK Boulder 26, 27, 29, 31, 33 - 40

There are also several collections that need more time to investigate do they bring something unique:
- Klaus & Reinhold Boulder Dash 1 - 10
- Klaus & Reinhold Boulder Dash 11 - 20
- Klaus & Reinhold Boulder Dash 21 - 30
- Klaus & Reinhold Boulder Dash 31 - 40
- NoOne All Games On One Disk 1 - 6
- NoOne All Games On One Disk 7 - 12
- NoOne All Games On One Disk 13 - 18
- NoOne Final Boulder 1 Speed Up Version
- NoOne Final Boulder 2 Speed Up Version

Other missing in GDash and present in your collection games I've already tried to open/extract/convert before.
For instance:

- Apollo8502 Boulder Dash + Construction Kit -- Could not import cave data -- unknown cave format!
- Boulder Dash 4 Screens -- all caves are empty after conversion
- Boulder_Dash_64000 -- Could not import cave data -- unknown cave format!
- Boulder Dash 99 A, B, C, D, G, H -- Could not import cave data -- unknown cave format!
- Boulder Dash 99 I, J, K, M -- Could not import cave data -- unknown cave format!
- Boulder Dash 1001 Unibit -- Could not import cave data -- unknown cave format!
- Boulder Dash Advanced TRC -- empty caves after conversion
- Boulder Dash Bosh -- Not family-friendly game
- Boulder Dash DTV -- Could not import cave data -- unknown cave format!
- Boulder Dashes Honz -- the game ends after start
- Boulder Dash The Lost Levels 2 -- syntax error on run ttl 2 -- syntax error in 48136
- Casey Boulder Dash 2000 -- empty caves after conversion
- GeekDash1 -- how to start the game?
- Marek Roth Crazy Dream 10 -- Could not import cave data -- unknown cave format!
- Match Buster --  Not family-friendly game
- Phoenix Runner Up Dash -- Could not import cave data -- unknown cave format!
- Ruben Spaans Boulder Dash 50 -- Could not import cave data -- unknown cave format!
- SPG's BoulderDash -- Could not import cave data -- unknown cave format!
- Super Boulder Dash -- Could not import cave data -- unknown cave format!
- Swedish Boulder Dash -- Could not import cave data -- unknown cave format!
- Wolfsoft Boulder Dash 9 & 12 -- Could not import cave data -- unknown cave format!

**Comment by renyxadarox** [comment]
https://github.com/revvv/gdash-export-CrLi/pull/48 new caves from cwscws's C64 Boulder Dash collection

**Comment by cwscws** [comment]
Crazy Dream 10 was done with the XDC Engine from Marek Roth, so the format is certainly different and is therefore not recognized by GDash. There are also new elements in it not available in GDash…

**Comment by zsommk** [comment]
CWS
Maybe you know something from LogicDeLuxe about its XDC engine?
I asked him on www.boulderdash.nl/forum many times about it, but there was no answer.

**Comment by cwscws** [comment]
There is a readme somewhere about CD10. I remember I read it. LogicDeLuxe is hard to reach, I know.

**Comment by cwscws** [comment]
Just a little info: Coolshaker Union Gang KG is Klaus Quindt. I was in contact with him about 18 years ago - he must be over 80 now if he is still alive…

**Comment by renyxadarox** [comment]
@cwscws 
CWS a.k.a. Claus Skrepek

**Comment by renyxadarox** [comment]
Regarding 

- Klaus & Reinhold Boulder Dash 1 - 10
- Klaus & Reinhold Boulder Dash 11 - 20
- Klaus & Reinhold Boulder Dash 21 - 30
- Klaus & Reinhold Boulder Dash 31 - 40

First of all, Klaus & Reinhold == The Magic Eye member Papis a.k.a Papi's.
When I converted all 40 cavesets, I found that:

- Papis\Boulder_Dash_01.gds == First_Star_Software\Boulder_Dash_1.gds
- Papis\Boulder_Dash_02.gds == First_Star_Software\Boulder_Dash_2.gds
- Papis\Boulder_Dash_03.gds ~= American_Action\Boulder_Dash_3.bd (different color palette)
- Papis\Boulder_Dash_04.gds == Dr_Watson\Dr_Watson_4.gds
- Papis\Boulder_Dash_06.gds == Don_Pedro\Boulderdash_VI.gds
- Papis\Boulder_Dash_07.gds == Don_Pedro\Boulderdash_VII.gds
- Papis\Boulder_Dash_08.gds == Don_Pedro\Boulderdash_VIII.gds
- Papis\Boulder_Dash_10.gds == Don_Pedro\Boulderdash_X.gds
- Papis\Boulder_Dash_11.gds == Don_Pedro\Boulderdash_XI.gds
- Papis\Boulder_Dash_16.gds == No_One\No_One_s_Boulder\No_One's_Boulder_16.gds
- Papis\Boulder_Dash_17.gds == No_One\No_One_s_Boulder\No_One's_Boulder_17.gds

So I added all except listed above.

**Comment by renyxadarox** [comment]
NoOne All Games On One Disk 1 - 6
NoOne All Games On One Disk 7 - 12
NoOne All Games On One Disk 13 - 18

==

\No_One\Final_Boulder\

--------------------------------------------

NoOne Final Boulder 2 Speed Up Version
contains also 2 different games

- BOULD.CHANGE1
- BOULD.CHANGE2

BOULD.CHANGE1 is almost equal to No_One\Boulder_Change_1.gds (different color palette)
So I decided to replace No_One\Boulder_Change_1.gds by a new one and add No_One\Boulder_Change_2.gds
