### ISSUE TITLE
GTK+ status bar not centered

### ISSUE THREAD

**Issue by zsommk** [revvv/gdash-export-CrLi#49]
Hi
I have such a problem
On OpenGL Gdash starts in the center of the screen and the diamond counter at the top is OK.
When I run GTK+ the game starts more to the left and the diamond counter moves to the right.
Moving the window causes the game to freeze.
Provides video from youtube

https://www.youtube.com/watch?v=wFB5MUekgVk

**Comment by revvv** [comment]
Yes, that was my optimization for centering the status bar in full cave view. Not sure why this is no longer required or why it's messing up normal mode. Reverted back.

**Comment by revvv** [comment]
> Moving the window causes the game to freeze.

You need to press ALT+Tab to get it back to work. I know this "feature" from the beginning...

**Comment by zsommk** [comment]
ALT+Tab helps.
I didn't know it.

Thank you
