### ISSUE TITLE
Quickly counting cave time

### ISSUE THREAD

**Issue by zsommk** [revvv/gdash-export-CrLi#50]
Such a non-committal improvement.
In BoulderDäsh by Guido Mersmann
you can speed up the countdown time.
When the cave has few seconds, it's not a problem.
When it has a lot, it takes a long time to wait for the next cave.

The video shows what it's like in BoulderDäsh
The cave has 999 seconds and you wait for it to count down. this can be accelerated with the FIRE key.
Or not have a countdown right away, entering from the cave exit with the FIRE key.

Here is the movie
https://www.youtube.com/watch?v=rKWLzKrkPtA

**Comment by renyxadarox** [comment]
BTW, I've noticed another issue related to Cave time.
Sometimes (always?) recorded videos are much longer then the Cave Time.
For example: https://youtu.be/cucIAqzmUvk
Cave Time = 255
The Video is 290 s long and the difference cannot be explained by intro and outro video segments.
In fact, the video from 0:00:05.467 to 0:04:46.167 has a duration 0:04:48.700 or ~ 288 s, while the Cave Time is reduced from 255 to 26, which is 229 s.
It seems that GDash timer is different from the system timer.

Maybe, it will be better to open a separate issue, right?

**Comment by revvv** [comment]
I'll think about it. In the meantime you could just hold 'f' for fast forward.

**Comment by zsommk** [comment]
Thank you. Yes, I know, I use this "F" key a lot, especially when the amoeba is growing up.

**Comment by cwscws** [comment]
I have to admit - I didn’t know about F

**Comment by renyxadarox** [comment]
> I have to admit - I didn’t know about F

You've never changed your keyboard settings )
Press **K** f̷o̷r̷ ̷r̷e̷s̷p̷e̷c̷t̷ on the Title Screen )

**Comment by cwscws** [comment]
I made the translation, so shame on me I never ever had the idea to try that!😎

**Comment by cwscws** [comment]
Nevertheless it would certainly be a nice idea to quickly count to zero when pressing the fire button while counting...

**Comment by renyxadarox** [comment]
I think it's better to reuse the Fast forward key (F by default), cause Fire key can be used to enter the cave exit.

**Comment by cwscws** [comment]
But this would effect only the counting after the cave exit has been entered.k

**Comment by revvv** [comment]
Fixed. Bonus should be added correctly.

**Comment by renyxadarox** [comment]
I don't like this new behaviour.
The Fire key is used for distance exit from a cave and I don't expect that the omitting final cave time counting depends on the way I exit the cave, by stepping to the exit or from 1 cell distance.
As I said before it would be better to assign Quick counting to Fast forward key (F by default).

**Comment by revvv** [comment]
Too bad. Ok, next release. I guess I also add ESC to skip. Not sure many people read the doc  and know about F.

**Comment by zsommk** [comment]
Thank you very much.
Now it's exactly like in BoulderDäsh by Guido Mersmann.
You are great.

**Comment by revvv** [comment]
New release it out... let me know if this is OK now.

**Comment by renyxadarox** [comment]
Nice.
