### ISSUE TITLE
Is it possible to improve scrolling smoothness in GTK+ mode?

### ISSUE THREAD

**Issue by BadDog73** [revvv/gdash-export-CrLi#58]
OpenGL mode looks much better than GTK+ mode but the lack of menu bar is a real minus.  I'd ditch GTK+ if I could but alternately scrolling could be improved, possibly?

**Comment by revvv** [comment]
No. For better scrolling use OpenGL.

**Comment by BadDog73** [comment]
Is it possible then to have Windows menus with any other graphics mode?

**Comment by revvv** [comment]
Well, that would require to refactor the code a lot. Simply no time for that.

**Comment by BadDog73** [comment]
I appreciate that you took the time to consider the request.  Thanks again.
