### ISSUE TITLE
GTK+ white instead of black background in fullscreen mode

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#61]
The background respectively the border around the game screen is white instead of black in GTK+ fullscreen mode.
<img width="640" alt="1" src="https://github.com/revvv/gdash-export-CrLi/assets/5362135/2c38a620-4f36-4a1d-8496-3ceb5075d88c">

**Comment by revvv** [comment]
Yes, this is a GTK default. Same white as the menubar background. I'll change it to black.
