### ISSUE TITLE
Atari soundset possible?

### ISSUE THREAD

**Issue by BadDog73** [revvv/gdash-export-CrLi#63]

**Comment by BadDog73** [comment]
I've extracted and converted most of the basic sounds.  It seems to work okay.

**Comment by revvv** [comment]
Well, attach them and we'll see.

**Comment by BadDog73** [comment]
Needs a little more work but dropping in files is somewhat serviceable.  I'm not sure if walk_empty and walk_earth are ever going to sound quite right.

**Comment by BadDog73** [comment]
Attached. As drop ins they're not terrible, but feel free to revise or whatever.

magic wall: sample's a little shorter than I wanted but it's not too bad

[sound.zip](https://github.com/revvv/gdash-export-CrLi/files/12614407/sound.zip)

**Comment by cwscws** [comment]
Are the samples from a real Atari or from an emulator?

**Comment by renyxadarox** [comment]
> a real Atari?

Recorded with a microphone?

**Comment by BadDog73** [comment]
They're sampled from YouTube.  So I assume an emulator.  I have an Atari 800XL in my closet but I don't have the equipment to get it to work, and I sort of doubt the floppies are any good either.  

From my recollection, the sounds I sampled are correct.

**Comment by cwscws** [comment]
I just watched a YouTube video of the Atari Boulder Dash. Compared to the C64 it sounds terrible
