### ISSUE TITLE
Extend the list of the main screen hints

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#67]
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/d4465cc5-47e9-4967-bc19-5d1e73fe85b0)

Space doesn't play, but asks "Enter your name".
Ctrl does play.

**Comment by renyxadarox** [comment]
In any case "Space" doesn't start playing.

**Comment by cwscws** [comment]
Hmmm. But where would you enter your name if not before starting a game? I think this is legitimate.

**Comment by renyxadarox** [comment]
I don't expect to be asked my name before the game starts at all.
I just press Ctrl and start playing right away.

**Comment by cwscws** [comment]
But how should the game know your name for the high scores?

**Comment by cwscws** [comment]
I entered a name which is used for the high scores

**Comment by cwscws** [comment]
But you are right. We should change "Space" to "Fire" as with the fire button you can start playing immediately, with space you have to enter your name first.

**Comment by zsommk** [comment]
Space - only name can be entered
Ctrl - play without name, but Windows will add the system name anyway
Enter - first name, second time Enter - play.

**Comment by renyxadarox** [comment]
@zsommk you are right, except Ctrl. This key is configurable as Key snap:
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/c71fa086-3f34-4874-b1e3-b17652339d1e)

**Comment by zsommk** [comment]
These are also the keys that work on the main screen:
"S" save caveset
"F" hall of fame
"T" caveset playing statistic

**Comment by renyxadarox** [comment]
These are also the keys that work on the cave:
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/91d93fb7-adb0-44cd-b5b1-ec4b9b2165c2)

And btw this Help appears after pressing H and you have to guess to press "H" to find out that "H" calls Help )))

So I guess it would be useful to add "H: help" to the main screen.

**Comment by renyxadarox** [comment]
> These are also the keys that work on the main screen: "S" save caveset "F" hall of fame "T" caveset playing statistic

There is also
"R" replays

And btw I noticed now that the main screen already shows all these hints (except T: statistics) and "H: help" instead of "X: errors" )

**Comment by renyxadarox** [comment]
> Space - only name can be entered

Enter after Space also starts playing.

**Comment by revvv** [comment]
Great report... I was sure I have seen a changing help footer some day... it disappeared, because there were errors logged.
I can't prevent that, because some updated libraries now always log some messages. Luckily I don't have to remove the log messages I have added ;-)

There is a complex rule set when to show which help footer:
1. If there is not enough space: No help footer
2. else if there were log messages, show "Crsr: select   Space: play   X: errors"
3. else show every 100 frames one of these lines:
    "Crsr: select   Space: play   H: help"
    "F: hall of fame  E: editor  R: replays" (editor only if it's GTK)
    "Joy: select   Fire: play" (but only if there is a joystick connected)

I'll fix it by removing rule 2.

**Comment by renyxadarox** [comment]
> I'll fix it by removing rule 2.

What about adding 5 new lines? (see https://github.com/revvv/gdash-export-CrLi/issues/67#issuecomment-1727162797)

**Comment by renyxadarox** [comment]
Well, what's so special in "F: hall of fame E: editor R: replays" line?
H shows them too...

**Comment by renyxadarox** [comment]
Ok, as you wish :-)

**Comment by renyxadarox** [comment]
**1.9.8**
Now 
"Crsr: select Space: play X: error"
"Crsr: select Space: play H: help"
"F: hall of fame E: editor R: replays"
rotate

**Comment by revvv** [comment]
I revised it again. Now the configured fire key is shown in the help footer:

1a. Cursor: Select    Control_L: Play (GTK)
1b. Cursor: Select    Left_Ctrl: Play (SDL)
2.  F: Hall of fame  E: Editor  H: Help
3.  Joystick: Select   Fire: Play

X: error was removed.
And actions are capitalized.

Hope you like it...
