### ISSUE TITLE
TitleScreenDirection

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#68]
Sometimes on an original C64 title screen tiles move not up, but down, for instance.

Add to .bd the optional TitleScreenDirection key in [game] section to specify the direction different than default (Up) from the predefined set of values: Up / Down / Left / Right.

Add Tile Direction dropdown list to Editor  Edit -> Caveset -> Cave set title image with Up (default) / Down / Left / Right values.

Move tiles to the TitleScreenDirection on the Title Screen.

**Comment by revvv** [comment]
Interesting proposal. Programming is no problem, but all the bureaucracy like adding the GUI elements etc... needs time...

**Comment by cwscws** [comment]
This is certainly nothing with high priority as it’s more like a gimmick than a function…

**Comment by renyxadarox** [comment]
Certainly, this is a low priority task.
But keep in mind, I'm interested to add title screens only while I'm playing the game.
It is unlikely that I will want to return to these cavesets later.
So... don't lower the priority too much! )

**Comment by renyxadarox** [comment]
/Boulderwilli/Midnight_Dash_1_L1.bd
/Boulderwilli/Midnight_Dash_1_L2.bd
/Boulderwilli/Midnight_Dash_1_L3.bd
/Boulderwilli/Midnight_Dash_1_L4.bd
/Boulderwilli/Midnight_Dash_1_L5.bd
/Boulderwilli/Midnight_Dash_2_L1.bd
/Boulderwilli/Midnight_Dash_2_L2.bd
/Boulderwilli/Midnight_Dash_2_L3.bd
/Boulderwilli/Midnight_Dash_2_L4.bd
/Boulderwilli/Midnight_Dash_2_L5.bd

TitleScreenDirection=Down

**Comment by revvv** [comment]
No time to implement. Sry.
