### ISSUE TITLE
Graphic themes missing

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#7]
The additional graphic themes from GDash are missing (boulder_rush.png, c64_gfx_bd2.png, c64_gfx.png). Best adding these to a separate folder called "themes".

**Comment by revvv** [comment]
Will be done in the next release. Have you noticed duplicate entries?
GDash will search for themes in installation directory and current directory and if they are identical (which is usually the case) we get duplicates. Don't really know how to avoid this without breaking the code...

**Comment by cwscws** [comment]
working now! :)
