### ISSUE TITLE
Editor: Save/Save as: add [highscore]

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#70]
Add [highscore] to .bd only if "Use BDCFF highscore" set to "yes".

**Comment by zsommk** [comment]
I played around with the high scores a bit.
I discovered that this "Use bdcff highscore" option does not work.
Whether it is set to "Yes" or "No", it does not work.
The result will only be saved when you use the "S" key on the title screen.
Moreover, the results are duplicated.
You can have more results than you played.
I found that even if you don't want the best results you will still have them, ".stat" files appear in Appdata
regardless of the desire to have them.
And you don't have to provide your name at all, Gdash copies it from the System.
In my opinion, something isn't right here.

**Comment by revvv** [comment]
> Moreover, the results are duplicated.

Could you describe a test scenario?

**Comment by renyxadarox** [comment]
> Moreover, the results are duplicated.

I think, if you completed a cave twice with the same result, [highscore] would contain both.

**Comment by zsommk** [comment]
I'm on vacation now, I can't make a film.
Apparently the *.stat file in Appdata copies the results from the *.bd file to itself and then Gdash sees it twice.

**Comment by revvv** [comment]
Released new version. Please verify.

**Comment by renyxadarox** [comment]
Works!
