### ISSUE TITLE
Alchemyst Dangerdash 03 out of date

### ISSUE THREAD

**Issue by thealtermaven** [revvv/gdash-export-CrLi#74]
I'm only posting this issue as the current archive has version 1 of Alchemyst Dangerdash 3. The current version is 1.01. Grab it from my BDCFF-sets section. Mark closed once you've committed. Thank you.

**Comment by revvv** [comment]
BDGB (Boulder Dash Game Base) contains the same version. Could you post a link?

**Comment by thealtermaven** [comment]
Apologies, you can find it [here](https://github.com/thealtermaven/BDCFF-sets/blob/main/Alchemyst%20Dangerdash%203.bd).
