### ISSUE TITLE
Found a negative side effect of previous bugfix

### ISSUE THREAD

**Issue by Dustin974** [revvv/gdash-export-CrLi#75]
It's about the boulder-wrapping thing. A non-falling boulder is not immediately allowed to wrap, that's fine in general, but I think an exception should be made for the very first frame. So if a boulder is initially placed on the bottom row and it can wrap at the start of the cave, then it should be allowed. 

I just noted that while testing a cave for a future release of mine. I designed this cave with an older GDash version and placed some boulders at the bottom row (as part of a big, endlessly falling boulder formation), and they're supposed to wrap immediately. Now with the newer GDash version, these boulders wrap only in the second frame, which changes the overall boulder formation and actually makes the cave unsolvable.

Of course I can fix my cave by giving the boulders a falling state at the beginning, then everything works fine again. But I still assume that this is an unwanted side effect, so I thought I'd share this here :)

**Comment by revvv** [comment]
I guess you are talking about #42. Glad that you found a workaround, because there is no fix except reverting #42.
