### ISSUE TITLE
Bug or feature: The butterfly doesn't explode when it touches the amoeba on the left

### ISSUE THREAD

**Issue by renyxadarox** [revvv/gdash-export-CrLi#76]
I found some interesting fluke: butterfly doesn't explode on amoeba, but locks it and turns it into diamonds:
https://youtu.be/x_guZQiXJrA

Two consecutive frames from the gameplay:
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/5db9715a-0cc5-4648-a969-9201fad6293f)
![image](https://github.com/revvv/gdash-export-CrLi/assets/42196270/57fe1e4f-12c4-4b28-b633-49dd0dca3c35)

**Comment by revvv** [comment]
Haven't checked C64 BD1 or CLKC, but I guess they have the same behavior:
If amoeba cannot grow any more it turns into diamonds. No matter what blocked the amoeba.

**Comment by renyxadarox** [comment]
Do you mean, the amoeba blocked with a butterfly on the right turns into diamonds, blocked with a butterfly left explodes?
Is this the case when the scanning order matter?

**Comment by revvv** [comment]
I'm pretty sure this would happen.

**Comment by renyxadarox** [comment]
I ran some tests to confirm my guess:
https://youtu.be/12klWUfNCZ8

**Comment by cwscws** [comment]
LogicDeLuxe acknowledged the behavior. This is regular physics.

http://www.gratissaugen.de/erbsen/exact.html
