### ISSUE TITLE
BoulderDash Unlimited Deluxe 1-3 Rebuild 2023

### ISSUE THREAD

**Issue by captainipxe** [revvv/gdash-export-CrLi#77]
[BoulderDash-UX-Trilogy.zip](https://github.com/revvv/gdash-export-CrLi/files/13521294/BoulderDash-UX-Trilogy.zip)

Hey there!

As mentioned i'll share my newest cavepacks here.

Sidenote: For some reason the amoeba grows faster in GDash compared to the C64 emulation.

You'll find screens of all caves at my downloadbox: https://downloadbox.captainpollutiontv.de/BoulderDash/

I hope you like these works :-)

**Comment by renyxadarox** [comment]
We already have [Boulderdash-UX](https://github.com/revvv/gdash-export-CrLi/tree/master/caves/UStar23) cavesets.
Are you cavesets a remastering of these?
What do you want your cavesets to have as an author, **UStar23**, **CaptainPollutionTV**, **captainipxe** or someone else?

**Comment by cwscws** [comment]
I read in the Boulder Dash forum that the games were updated. I think we should replace the existing ones with these.

**Comment by captainipxe** [comment]
> We already have [Boulderdash-UX](https://github.com/revvv/gdash-export-CrLi/tree/master/caves/UStar23) cavesets. Are your cavesets a remastering of these? What do you want your cavesets to have as an author, **UStar23**, **CaptainPollutionTV**, **captainipxe** or someone else?

I'd say CaptainPollutionTV because thats my creative nickname since 2015 and going on. :)

I did fix some bugs and update caves. So it is a newer version.

I want to say that the amoeba grows faster in GDash compared to a real C64 / emulation.

**Comment by revvv** [comment]
What's the status?
