### ISSUE TITLE
Frusti Dash: Special effects don't work

### ISSUE THREAD

**Issue by Dustin974** [revvv/gdash-export-CrLi#78]
Hi, I just noted that the game "Frusti Dash" (in folder \Frust) has special effects which don't work in GDash:
- in cave O (the empty cave), snapping should create amoeba.
- - in cave P, falling boulders should convert into diamonds, then after falling again, into butterflies.
- There might be more in the game.
- I wonder why these don't work although GDash does support those special effects?!  Maybe it's because the game was created with BD1 engine, and it might be the only BD1 engine game with special effects?!
- Anyway, I would be willing to fix Frusti Dash so it works on GDash. Would you then release it? :)
- Cheers, Dustin
P.S.: Thanks a lot for all your work with GDash!!!

**Comment by revvv** [comment]
Hi, yes please fix it. I'll check it in, of course. A release might take a while, but as long as there are only cave updates I guess it's ok, because you can always download the project and replace the caves of your installation.

**Comment by Dustin974** [comment]
Alright, super! I've just discovered another bug: in \Peter Metsemaker, "Metsemakers Dash.brc", cave A, the amoeba does not grow. Probably a compatibility problem with .brc files (luckily there aren't any others in the CAVES folder afaik). I'm going to fix that one too, and check the rest of that game as well.

**Comment by Dustin974** [comment]
Hi, now I tested all Frusti Dash caves (in original) and 2 caves feature effects which (1) I've never seen before and (2) I doubt they're compatible with GDash:
(1) cave M: If the amoeba is trapped, it turns into fireflies - so far, so clear. But when a firefly gets crushed by a boulder, strange things are happening: sometimes it just explodes into dust as normal, but sometimes it generates butterflies and/or diamonds. 
(2) cave N: The amoeba does not grow in a normal way, but instead it produces boulders, while the amoeba itself always stays at size 1.
Frusti must have had a lot of fun hacking the engine :D But as I see it, GDash does not support these effects (and in case of (1), I haven't even understood the exact rules!)

Does anyone know more about that? :D
