### ISSUE TITLE
Teleporter problem

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#79]
The Teleporter is not working correctly when entering it from left or from top. It works perfectly from down and right.

**Comment by revvv** [comment]
I guess you are just surprised how the teleporter works. I guess LogicDeluxe invented it, so I just describe what I have observed:
- Dirt/boulders etc. block a teleporter. (If the target teleporter has dirt at its exist, no teleporting)
- Entering source teleporter from the left => exit target teleporter on the right (vice versa)
- Entering source teleporter from the top => exit target teleporter on the bottom (vice versa)
- The target teleporter is determined this way: Starting from Rockford's location the next teleporer is searched row by row. When the level end is reached, it is started from the beginning. Only a teleporter which is not blocked on the appropriate exit is considered. And even the source teleporter might be the target teleporter!

In doubt, check C64 Crazy Light Engine!

I guess you have two teleporters which have spaces on their sides.
Entering from the left: Looks like walking through? Yes, according to spec this is correct.
Entering from the top? See yourself ;-)

**Comment by cwscws** [comment]
The teleporter behavior is certainly well-conceived but on the other side it’s not fully logical for regular players.

**Comment by revvv** [comment]
When I played around with the teleporter I was surprised, too. Then I checked some of the original C64 caves and I saw that the behavior is intended. I can only speculate why the teleporter behaves like this: Maybe easier to implement on C64? And if the most exists are blocked with steel walls, you may not notice it.
