### ISSUE TITLE
Problems to install via $ make install

### ISSUE THREAD

**Issue by herz-aus-gold-42** [revvv/gdash-export-CrLi#83]
using MSYS2 (Win10 or Win11) for configure and make .. this works fine
but "make install" stop with an error:

`/usr/bin/mkdir -p '/ucrt64/share/gdash/caves/Alex_Zop'
 /usr/bin/install -c -m 644 Alex_Zop/Alex_Zop.gds Alex_Zop/Nahost_91.bd Alex_Zop/Rockford_in_Nimmerland_2.bd Alex_Zop/Rocki_Rockano_in_Lolli_Land_01.bd '/ucrt64/share/gdash/caves/Alex_Zop'
/bin/sh: -c: line 11: unexpected EOF while looking for matching `''
make[2]: *** [Makefile:2329: install-Arno_WeberDATA] Error 2
make[2]: Leaving directory '/home/training/gdash-export-CrLi/caves'
make[1]: *** [Makefile:6075: install-am] Error 2
make[1]: Leaving directory '/home/training/gdash-export-CrLi/caves'
make: *** [Makefile:492: install-recursive] Error 1
`
taking a look into the makefile for caves -> i think maybe a variable is missed.

btw. is it possible to change "make install" so it install all without the caves.
and "make install caves" for the caves?

**Comment by herz-aus-gold-42** [comment]
Found: CaveSets with ' in filename are the problem. Like in "No_One's_Boulder_10.gds"
Rename all CaveSets and remove ' in Makefile -> install do the job now

**Comment by revvv** [comment]
Thanks for the finding. I renamed the cave files and updated the Makefiles. Hopefully this will do it.
(As stated in [README.md](https://github.com/revvv/gdash-export-CrLi/blob/master/README.md) I don't use _make install_)

**Comment by herz-aus-gold-42** [comment]
closed
