### ISSUE TITLE
Update Alchemyst_Dangerdash_4.bd

### ISSUE THREAD

**Issue by thealtermaven** [revvv/gdash-export-CrLi#89]
A few initial release errors were discovered in Alchemyst Dig 04 that had to be fixed as I'm gearing it for the BDGB release. It should be solid now barring any last minute detections. Mark as solved when you've updated the file.

**Comment by revvv** [comment]
Could you please give me a download link?
We have already this version:
https://github.com/thealtermaven/BDCFF-sets/blob/main/Alchemyst%20Dig%204.bd

**Comment by thealtermaven** [comment]
Oops, it's not Alchemyst Dig 4. It's DangerDash 4, it's 1.02. I am very sorry.
https://github.com/thealtermaven/BDCFF-sets/blob/main/Alchemyst%20Dangerdash%204.bd
