### ISSUE TITLE
GDash crashes when trying to set cave colours when selecting a palette other than RGB.

### ISSUE THREAD

**Issue by benjamind2008** [revvv/gdash-export-CrLi#9]
I go to edit a cave, and try to select a colour that is based on a palette, say Atari, or C64DTV, and it just crashes GDash.

This is definitely some kind of bug, possibly a memory exception, or a general protection fault. It simply crashes, I haven't had any time to look at the code, since I'm mostly working on other projects, but I'm assuming this is a GPF or a page fault. The GDash window just checks out as though one clicked the exit button.

**Comment by revvv** [comment]
Thank you for finding this bug. Maybe it's worth not to ignore the compiler warnings ;-)
